// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateAccountData, CreateAccountErrors, CreateAccountResponses, CreateBusinessData, CreateBusinessErrors, CreateBusinessResponses, DeleteAccountByIdData, DeleteAccountByIdErrors, DeleteAccountByIdResponses, GetAccountByIdData, GetAccountByIdErrors, GetAccountByIdResponses, GetAccountsData, GetAccountsErrors, GetAccountsResponses, GetBusinessByIdData, GetBusinessByIdErrors, GetBusinessByIdResponses, LoginAccountData, LoginAccountErrors, LoginAccountResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get accounts
 *
 * Get accounts based on user's role. A business owner or employee sees all accounts for their business. An individual user sees only their own account.
 */
export const getAccounts = <ThrowOnError extends boolean = false>(options?: Options<GetAccountsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAccountsResponses, GetAccountsErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/account',
        ...options
    });
};

/**
 * Create account
 *
 * Create a new account. If creating an account for a business, authentication is required and the user must be the business owner.
 */
export const createAccount = <ThrowOnError extends boolean = false>(options: Options<CreateAccountData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateAccountResponses, CreateAccountErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/account',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Log in to account
 *
 * Log in to account
 */
export const loginAccount = <ThrowOnError extends boolean = false>(options: Options<LoginAccountData, ThrowOnError>) => {
    return (options.client ?? client).post<LoginAccountResponses, LoginAccountErrors, ThrowOnError>({
        responseType: 'json',
        url: '/account/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete an account
 *
 * Delete an account. Users can delete their own account. Business owners can delete employee accounts.
 */
export const deleteAccountById = <ThrowOnError extends boolean = false>(options: Options<DeleteAccountByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteAccountByIdResponses, DeleteAccountByIdErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/account/{id}',
        ...options
    });
};

/**
 * Get account information
 *
 * Get account information. Users can get their own account, or any account within their business if they are an owner or employee.
 */
export const getAccountById = <ThrowOnError extends boolean = false>(options: Options<GetAccountByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetAccountByIdResponses, GetAccountByIdErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/account/{id}',
        ...options
    });
};

/**
 * Create a business
 *
 * Create a business with the provided details
 */
export const createBusiness = <ThrowOnError extends boolean = false>(options: Options<CreateBusinessData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateBusinessResponses, CreateBusinessErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/business',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get business information
 *
 * Get business information
 */
export const getBusinessById = <ThrowOnError extends boolean = false>(options: Options<GetBusinessByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetBusinessByIdResponses, GetBusinessByIdErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/business/{id}',
        ...options
    });
};
