// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8080' | (string & {});
};

export type ConstantsAccessLevel = 'Read' | 'Write';

export type ConstantsAccountRoleLinkStatus = 'Active' | 'Suspended' | 'Deactivated';

export type ConstantsAction = 'accounts' | 'businesses' | 'roles';

export type ModelsAccountDto = {
    businessId?: number;
    id?: number;
    name?: string;
    roles?: Array<ModelsAccountRoleLinkDto>;
    username?: string;
};

export type ModelsAccountRoleDto = {
    businessId?: number;
    functionLinks?: Array<ModelsAccountRoleFunctionLinkDto>;
    id?: number;
    name?: string;
};

export type ModelsAccountRoleFunctionLinkDto = {
    accessLevels?: Array<ConstantsAccessLevel>;
    function?: ModelsFunctionDto;
    id?: number;
};

export type ModelsAccountRoleLinkDto = {
    id?: number;
    role?: ModelsAccountRoleDto;
    status?: ConstantsAccountRoleLinkStatus;
};

export type ModelsAssignFunctionRequest = {
    accessLevels: Array<ConstantsAccessLevel>;
    functionId: number;
};

export type ModelsAssignRoleRequest = {
    roleId: number;
};

export type ModelsBusinessDto = {
    address?: string;
    email?: string;
    id?: number;
    name?: string;
    phone?: string;
};

export type ModelsCreateAccountRequest = {
    businessId?: number;
    name: string;
    password: string;
    username: string;
};

export type ModelsCreateAccountRoleRequest = {
    businessId: number;
    name: string;
};

export type ModelsCreateBusinessRequest = {
    address: string;
    email: string;
    name: string;
    phone: string;
};

export type ModelsFunctionDto = {
    action?: ConstantsAction;
    description?: string;
    id?: number;
    name?: string;
};

export type ModelsHttpError = {
    error?: string;
};

export type ModelsLoginRequest = {
    password: string;
    username: string;
};

export type ModelsUpdateAccountRoleLinkRequest = {
    status: 'Active' | 'Suspended' | 'Deactivated';
};

export type ModelsUpdateAccountRoleRequest = {
    name: string;
};

export type CreateAccountData = {
    /**
     * Account to create
     */
    body: ModelsCreateAccountRequest;
    path?: never;
    query?: never;
    url: '/account';
};

export type CreateAccountErrors = {
    /**
     * Bad Request
     */
    400: ModelsHttpError;
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Forbidden
     */
    403: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type CreateAccountError = CreateAccountErrors[keyof CreateAccountErrors];

export type CreateAccountResponses = {
    /**
     * Created
     */
    201: ModelsAccountDto;
};

export type CreateAccountResponse = CreateAccountResponses[keyof CreateAccountResponses];

export type GetAllFunctionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/functions';
};

export type GetAllFunctionsErrors = {
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Forbidden
     */
    403: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type GetAllFunctionsError = GetAllFunctionsErrors[keyof GetAllFunctionsErrors];

export type GetAllFunctionsResponses = {
    /**
     * OK
     */
    200: Array<ModelsFunctionDto>;
};

export type GetAllFunctionsResponse = GetAllFunctionsResponses[keyof GetAllFunctionsResponses];

export type LoginAccountData = {
    /**
     * Login credentials
     */
    body: ModelsLoginRequest;
    path?: never;
    query?: never;
    url: '/account/login';
};

export type LoginAccountErrors = {
    /**
     * Bad Request
     */
    400: ModelsHttpError;
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
};

export type LoginAccountError = LoginAccountErrors[keyof LoginAccountErrors];

export type LoginAccountResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type LoginAccountResponse = LoginAccountResponses[keyof LoginAccountResponses];

export type GetMyAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/me';
};

export type GetMyAccountErrors = {
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Not Found
     */
    404: ModelsHttpError;
};

export type GetMyAccountError = GetMyAccountErrors[keyof GetMyAccountErrors];

export type GetMyAccountResponses = {
    /**
     * OK
     */
    200: ModelsAccountDto;
};

export type GetMyAccountResponse = GetMyAccountResponses[keyof GetMyAccountResponses];

export type CreateAccountRoleData = {
    /**
     * Account role to create
     */
    body: ModelsCreateAccountRoleRequest;
    path?: never;
    query?: never;
    url: '/account/role';
};

export type CreateAccountRoleErrors = {
    /**
     * Bad Request
     */
    400: ModelsHttpError;
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Forbidden
     */
    403: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type CreateAccountRoleError = CreateAccountRoleErrors[keyof CreateAccountRoleErrors];

export type CreateAccountRoleResponses = {
    /**
     * Created
     */
    201: ModelsAccountRoleDto;
};

export type CreateAccountRoleResponse = CreateAccountRoleResponses[keyof CreateAccountRoleResponses];

export type DeleteAccountRoleByIdData = {
    body?: never;
    path: {
        /**
         * Role ID
         */
        id: number;
    };
    query?: never;
    url: '/account/role/{id}';
};

export type DeleteAccountRoleByIdErrors = {
    /**
     * Bad Request
     */
    400: ModelsHttpError;
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Forbidden
     */
    403: ModelsHttpError;
    /**
     * Not Found
     */
    404: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type DeleteAccountRoleByIdError = DeleteAccountRoleByIdErrors[keyof DeleteAccountRoleByIdErrors];

export type DeleteAccountRoleByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetAccountRoleByIdData = {
    body?: never;
    path: {
        /**
         * Role ID
         */
        id: number;
    };
    query?: never;
    url: '/account/role/{id}';
};

export type GetAccountRoleByIdErrors = {
    /**
     * Bad Request
     */
    400: ModelsHttpError;
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Forbidden
     */
    403: ModelsHttpError;
    /**
     * Not Found
     */
    404: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type GetAccountRoleByIdError = GetAccountRoleByIdErrors[keyof GetAccountRoleByIdErrors];

export type GetAccountRoleByIdResponses = {
    /**
     * OK
     */
    200: ModelsAccountRoleDto;
};

export type GetAccountRoleByIdResponse = GetAccountRoleByIdResponses[keyof GetAccountRoleByIdResponses];

export type UpdateAccountRoleByIdData = {
    /**
     * Role to update
     */
    body: ModelsUpdateAccountRoleRequest;
    path: {
        /**
         * Role ID
         */
        id: number;
    };
    query?: never;
    url: '/account/role/{id}';
};

export type UpdateAccountRoleByIdErrors = {
    /**
     * Bad Request
     */
    400: ModelsHttpError;
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Forbidden
     */
    403: ModelsHttpError;
    /**
     * Not Found
     */
    404: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type UpdateAccountRoleByIdError = UpdateAccountRoleByIdErrors[keyof UpdateAccountRoleByIdErrors];

export type UpdateAccountRoleByIdResponses = {
    /**
     * OK
     */
    200: ModelsAccountRoleDto;
};

export type UpdateAccountRoleByIdResponse = UpdateAccountRoleByIdResponses[keyof UpdateAccountRoleByIdResponses];

export type GetFunctionsForRoleData = {
    body?: never;
    path: {
        /**
         * Role ID
         */
        id: number;
    };
    query?: never;
    url: '/account/role/{id}/function';
};

export type GetFunctionsForRoleErrors = {
    /**
     * Bad Request
     */
    400: ModelsHttpError;
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Forbidden
     */
    403: ModelsHttpError;
    /**
     * Not Found
     */
    404: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type GetFunctionsForRoleError = GetFunctionsForRoleErrors[keyof GetFunctionsForRoleErrors];

export type GetFunctionsForRoleResponses = {
    /**
     * OK
     */
    200: Array<ModelsAccountRoleFunctionLinkDto>;
};

export type GetFunctionsForRoleResponse = GetFunctionsForRoleResponses[keyof GetFunctionsForRoleResponses];

export type AssignFunctionToRoleData = {
    /**
     * Function to assign
     */
    body: ModelsAssignFunctionRequest;
    path: {
        /**
         * Role ID
         */
        id: number;
    };
    query?: never;
    url: '/account/role/{id}/function';
};

export type AssignFunctionToRoleErrors = {
    /**
     * Bad Request
     */
    400: ModelsHttpError;
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Forbidden
     */
    403: ModelsHttpError;
    /**
     * Not Found
     */
    404: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type AssignFunctionToRoleError = AssignFunctionToRoleErrors[keyof AssignFunctionToRoleErrors];

export type AssignFunctionToRoleResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetAccountsData = {
    body?: never;
    path: {
        /**
         * Business ID
         */
        businessId: number;
    };
    query?: never;
    url: '/account/{businessId}';
};

export type GetAccountsErrors = {
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type GetAccountsError = GetAccountsErrors[keyof GetAccountsErrors];

export type GetAccountsResponses = {
    /**
     * OK
     */
    200: Array<ModelsAccountDto>;
};

export type GetAccountsResponse = GetAccountsResponses[keyof GetAccountsResponses];

export type DeleteAccountByIdData = {
    body?: never;
    path: {
        /**
         * Account ID
         */
        id: number;
    };
    query?: never;
    url: '/account/{id}';
};

export type DeleteAccountByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Forbidden
     */
    403: ModelsHttpError;
    /**
     * Not Found
     */
    404: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type DeleteAccountByIdError = DeleteAccountByIdErrors[keyof DeleteAccountByIdErrors];

export type DeleteAccountByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type AssignRoleToAccountData = {
    /**
     * Role to assign
     */
    body: ModelsAssignRoleRequest;
    path: {
        /**
         * Account ID
         */
        id: number;
    };
    query?: never;
    url: '/account/{id}/role';
};

export type AssignRoleToAccountErrors = {
    /**
     * Bad Request
     */
    400: ModelsHttpError;
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Forbidden
     */
    403: ModelsHttpError;
    /**
     * Not Found
     */
    404: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type AssignRoleToAccountError = AssignRoleToAccountErrors[keyof AssignRoleToAccountErrors];

export type AssignRoleToAccountResponses = {
    /**
     * Created
     */
    201: ModelsAccountRoleLinkDto;
};

export type AssignRoleToAccountResponse = AssignRoleToAccountResponses[keyof AssignRoleToAccountResponses];

export type UpdateAccountRoleStatusData = {
    /**
     * New status
     */
    body: ModelsUpdateAccountRoleLinkRequest;
    path: {
        /**
         * Account ID
         */
        id: number;
        /**
         * Role ID
         */
        roleId: number;
    };
    query?: never;
    url: '/account/{id}/role/{roleId}';
};

export type UpdateAccountRoleStatusErrors = {
    /**
     * Bad Request
     */
    400: ModelsHttpError;
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Forbidden
     */
    403: ModelsHttpError;
    /**
     * Not Found
     */
    404: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type UpdateAccountRoleStatusError = UpdateAccountRoleStatusErrors[keyof UpdateAccountRoleStatusErrors];

export type UpdateAccountRoleStatusResponses = {
    /**
     * OK
     */
    200: ModelsAccountRoleLinkDto;
};

export type UpdateAccountRoleStatusResponse = UpdateAccountRoleStatusResponses[keyof UpdateAccountRoleStatusResponses];

export type GetBusinessesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/business';
};

export type GetBusinessesErrors = {
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type GetBusinessesError = GetBusinessesErrors[keyof GetBusinessesErrors];

export type GetBusinessesResponses = {
    /**
     * OK
     */
    200: Array<ModelsBusinessDto>;
};

export type GetBusinessesResponse = GetBusinessesResponses[keyof GetBusinessesResponses];

export type CreateBusinessData = {
    /**
     * Business to create
     */
    body: ModelsCreateBusinessRequest;
    path?: never;
    query?: never;
    url: '/business';
};

export type CreateBusinessErrors = {
    /**
     * Bad Request
     */
    400: ModelsHttpError;
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type CreateBusinessError = CreateBusinessErrors[keyof CreateBusinessErrors];

export type CreateBusinessResponses = {
    /**
     * Created
     */
    201: ModelsBusinessDto;
};

export type CreateBusinessResponse = CreateBusinessResponses[keyof CreateBusinessResponses];

export type GetBusinessByIdData = {
    body?: never;
    path: {
        /**
         * Business ID
         */
        id: number;
    };
    query?: never;
    url: '/business/{id}';
};

export type GetBusinessByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Forbidden
     */
    403: ModelsHttpError;
    /**
     * Not Found
     */
    404: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type GetBusinessByIdError = GetBusinessByIdErrors[keyof GetBusinessByIdErrors];

export type GetBusinessByIdResponses = {
    /**
     * OK
     */
    200: ModelsBusinessDto;
};

export type GetBusinessByIdResponse = GetBusinessByIdResponses[keyof GetBusinessByIdResponses];

export type GetBusinessRolesData = {
    body?: never;
    path: {
        /**
         * Business ID
         */
        id: number;
    };
    query?: never;
    url: '/business/{id}/roles';
};

export type GetBusinessRolesErrors = {
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Forbidden
     */
    403: ModelsHttpError;
    /**
     * Not Found
     */
    404: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type GetBusinessRolesError = GetBusinessRolesErrors[keyof GetBusinessRolesErrors];

export type GetBusinessRolesResponses = {
    /**
     * OK
     */
    200: Array<ModelsAccountRoleDto>;
};

export type GetBusinessRolesResponse = GetBusinessRolesResponses[keyof GetBusinessRolesResponses];
