// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'localhost:8080/' | (string & {});
};

export type EntitiesAccount = {
    business?: EntitiesBusiness;
    identAccount?: number;
    identBusiness?: number;
    name?: string;
    username?: string;
};

export type EntitiesBusiness = {
    address?: string;
    email?: string;
    identBusiness?: number;
    identOwnerAccount?: number;
    name?: string;
    ownerAccount?: EntitiesAccount;
    phone?: string;
};

export type ModelsBusinessResponse = {
    address: string;
    email: string;
    identBusiness: number;
    name: string;
    ownerAccount?: ModelsOwnerAccountResponse;
    phone: string;
};

export type ModelsCreateAccountRequest = {
    identBusiness?: number;
    name: string;
    password: string;
    username: string;
};

export type ModelsCreateBusinessRequest = {
    address: string;
    email: string;
    name: string;
    phone: string;
};

export type ModelsHttpError = {
    error?: string;
};

export type ModelsLoginRequest = {
    password: string;
    username: string;
};

export type ModelsOwnerAccountResponse = {
    identAccount?: number;
    name?: string;
    username?: string;
};

export type GetAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type GetAccountsErrors = {
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type GetAccountsError = GetAccountsErrors[keyof GetAccountsErrors];

export type GetAccountsResponses = {
    /**
     * OK
     */
    200: Array<EntitiesAccount>;
};

export type GetAccountsResponse = GetAccountsResponses[keyof GetAccountsResponses];

export type CreateAccountData = {
    /**
     * Account to create
     */
    body: ModelsCreateAccountRequest;
    path?: never;
    query?: never;
    url: '/account';
};

export type CreateAccountErrors = {
    /**
     * Bad Request
     */
    400: ModelsHttpError;
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Forbidden
     */
    403: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type CreateAccountError = CreateAccountErrors[keyof CreateAccountErrors];

export type CreateAccountResponses = {
    /**
     * Created
     */
    201: EntitiesAccount;
};

export type CreateAccountResponse = CreateAccountResponses[keyof CreateAccountResponses];

export type LoginAccountData = {
    /**
     * Login credentials
     */
    body: ModelsLoginRequest;
    path?: never;
    query?: never;
    url: '/account/login';
};

export type LoginAccountErrors = {
    /**
     * Bad Request
     */
    400: ModelsHttpError;
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
};

export type LoginAccountError = LoginAccountErrors[keyof LoginAccountErrors];

export type LoginAccountResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type LoginAccountResponse = LoginAccountResponses[keyof LoginAccountResponses];

export type DeleteAccountByIdData = {
    body?: never;
    path: {
        /**
         * Account ID
         */
        id: number;
    };
    query?: never;
    url: '/account/{id}';
};

export type DeleteAccountByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Forbidden
     */
    403: ModelsHttpError;
    /**
     * Not Found
     */
    404: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type DeleteAccountByIdError = DeleteAccountByIdErrors[keyof DeleteAccountByIdErrors];

export type DeleteAccountByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetAccountByIdData = {
    body?: never;
    path: {
        /**
         * Account ID
         */
        id: number;
    };
    query?: never;
    url: '/account/{id}';
};

export type GetAccountByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Forbidden
     */
    403: ModelsHttpError;
    /**
     * Not Found
     */
    404: ModelsHttpError;
};

export type GetAccountByIdError = GetAccountByIdErrors[keyof GetAccountByIdErrors];

export type GetAccountByIdResponses = {
    /**
     * OK
     */
    200: EntitiesAccount;
};

export type GetAccountByIdResponse = GetAccountByIdResponses[keyof GetAccountByIdResponses];

export type CreateBusinessData = {
    /**
     * Business to create
     */
    body: ModelsCreateBusinessRequest;
    path?: never;
    query?: never;
    url: '/business';
};

export type CreateBusinessErrors = {
    /**
     * Bad Request
     */
    400: ModelsHttpError;
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type CreateBusinessError = CreateBusinessErrors[keyof CreateBusinessErrors];

export type CreateBusinessResponses = {
    /**
     * Created
     */
    201: ModelsBusinessResponse;
};

export type CreateBusinessResponse = CreateBusinessResponses[keyof CreateBusinessResponses];

export type GetBusinessByIdData = {
    body?: never;
    path: {
        /**
         * Business ID
         */
        id: number;
    };
    query?: never;
    url: '/business/{id}';
};

export type GetBusinessByIdErrors = {
    /**
     * Unauthorized
     */
    401: ModelsHttpError;
    /**
     * Forbidden
     */
    403: ModelsHttpError;
    /**
     * Not Found
     */
    404: ModelsHttpError;
    /**
     * Internal Server Error
     */
    500: ModelsHttpError;
};

export type GetBusinessByIdError = GetBusinessByIdErrors[keyof GetBusinessByIdErrors];

export type GetBusinessByIdResponses = {
    /**
     * OK
     */
    200: ModelsBusinessResponse;
};

export type GetBusinessByIdResponse = GetBusinessByIdResponses[keyof GetBusinessByIdResponses];
